[theme]
primaryColor = "#FF69B4"  # Hot Pink
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#FFE4E1"  # Misty Rose for a soft pink secondary background
textColor = "#FF1493"  # Deep Pink text color
font = "sans serif"  # Optional: Choose a font like sans serif
